### ISSUE TITLE
Please donate this to the ASF

### ISSUE THREAD

**Issue by codefromthecrypt** [takari/takari-maven-plugin#18]
The several hundred lines of goodness here is great, but current enforcement policy of the apache incubator makes it a bit of a liability. Whether you agree with me or others or not, you can probably imagine that being forced to have this in the NOTICE file can be off-putting to certain contributors.

https://lists.apache.org/thread.html/26bbc663ce6f81125110234b30c1ddf63d4ab2a03da408bc9fe07563@%3Cgeneral.incubator.apache.org%3E

One way out is to donate this or a copy of it to the ASF. Are you willing to do that?

**Comment by mosabua** [comment]
I updated the license header. We can not donate this to the ASF since copyright is owned by all contributors and hence distributed and we can not transfer ownership without contacting all contributors. That would be pretty much impossible at this stage. Also.. I dont understand what the actual problem is .. just add the project to the notice file and you are done.
