### ISSUE TITLE
maven-wrapper.properties refers to tar.gz archive instead of jar

### ISSUE THREAD

**Issue by pzygielo** [takari/takari-maven-plugin#19]
`.mvn/wrapper/maven-wrapper.properties` generated by [0.7.2](https://github.com/takari/takari-maven-plugin/releases/tag/maven-0.7.2) points to
> wrapperUrl=https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.2/maven-wrapper-0.5.2.tar.gz

(note `tar.gz` extension), which is [being downloaded if missing](https://travis-ci.org/pzrep/mvn-wrapper-targz/jobs/497224218#L614) (expected action if repository does not store it I presume) while `jar` is expected [later](https://travis-ci.org/pzrep/mvn-wrapper-targz/jobs/497224218#L628).

**Comment by mosabua** [comment]
This seems fine in master and in 0.7.3 ... can you confirm please?

**Comment by mosabua** [comment]
Hm... seems to be some problem going on during install or so ... have to check it out in more detail. Feel free to send a PR if you beat me to it.

**Comment by mosabua** [comment]
master in maven-wrapper is correct. 
https://github.com/takari/maven-wrapper/blob/master/.mvn/wrapper/maven-wrapper.properties#L2

**Comment by mosabua** [comment]
so is 0.5.3 tag

https://github.com/takari/maven-wrapper/blob/maven-wrapper-0.5.3/.mvn/wrapper/maven-wrapper.properties

So I am pretty sure the takari maven plugin messes this up on install or something else is going on during install (or somehow the binary gets the wrong content) .. will have to check

**Comment by mosabua** [comment]
the culprit is that the tar.gz is downloaded

https://github.com/takari/takari-maven-plugin/blob/master/src/main/java/io/takari/maven/plugins/WrapperMojo.java#L63

and then that is used to set the URL in the wrapper properties file  

https://github.com/takari/takari-maven-plugin/blob/master/src/main/java/io/takari/maven/plugins/WrapperMojo.java#L101

have to update to use the .jar there instead of .tar.gz ... maybe just a replace ... cant do that now though

**Comment by pzygielo** [comment]
Thanks - 0.7.4 [works fine](https://travis-ci.org/pzrep/mvn-wrapper-targz/builds/498558569).
:fireworks:
